# Generated by Django 5.1.3 on 2024-11-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='login_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='update_time',
        ),
    ]
