# Generated by Django 5.1.3 on 2024-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
